classDiagram
    direction TB

    %% ENUMERACIONES
    class T_Rol {
        <<enumeration>>
        Jefe_catedra
        Ayudante
    }
    class T_Materia {
        <<enumeration>>
        Obligatoria
        Electiva
    }
    class T_Estado {
        <<enumeration>>
        Vigente
        Cerrado
    }
    class T_Telefono {
        <<enumeration>>
        fijo
        Celular
    }
    class T_nivel {
        <<enumeration>>
        Avanzado
        Ingresante
    }
    class T_Periodo {
        <<enumeration>>
        cuatrimestre
        bimestre
        año
    }

    %% CLASES
    class Persona {
        -int DNI
        -char Nombre
        -char Apellido
        -T_Telefono Telefono
    }
    class Estudiante {
        -int cod_estudiante
    }
    class Profesor {
        -int nro_legajo
    }
    class materia {
        -int CodMateria
        -char Nombre
        -boolean Obligatoria
    }
    class Carrera {
        -char Nombre
        -int Codigo
    }
    class Plan_Estudio {
        -int IDPlan
        -T_Estado Estado
        -int version
    }

    %% CLASES DE ASOCIACIÓN
    class Examen_Final {
        -int Nota_final
        -int Fecha
    }
    class rol_periodo {
        -T_Periodo Periodo
        -T_Rol rol
    }
    class Nivel {
        -T_nivel Nivel
    }
    class Coorrelativa {
        -boolean Disponibilidad
    }

    %% RELACIONES
    Persona <|-- Estudiante
    Persona <|-- Profesor

    %% Relaciones Profesor - Materia
    Profesor "1" -- "1..*" materia : Responsable
    Profesor "1..*" -- "0..*" materia
    rol_periodo .. Profesor
    rol_periodo .. materia

    %% Relaciones Estudiante - Materia
    Estudiante "1..*" -- "0..*" materia : Cursa
    Estudiante "1..*" -- "0..*" materia : Examen_Final
    Examen_Final .. Estudiante
    Examen_Final .. materia

    %% Relaciones Materia - Plan (Agregación)
    Plan_Estudio "1..*" o-- "1..*" materia

    %% Relaciones Plan - Carrera
    Plan_Estudio "1..*" -- "1" Carrera

    %% Relaciones Estudiante - Carrera / Plan
    Estudiante "1..*" -- "1..*" Carrera
    Nivel .. Estudiante
    Nivel .. Carrera
    Estudiante "0..*" -- "1..*" Plan_Estudio

    %% Relación Recursiva
    materia "0..*" -- "0..*" materia : coorrelativa
    Coorrelativa .. materia