com.is1.proyecto.models.Student:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.Professor:default
com.is1.proyecto.models.Dictated:default
com.is1.proyecto.models.Enrollment:default
com.is1.proyecto.models.Course:default
